// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {killer} from '../models';
import {app} from '../models';

export function KillService(arg1:killer.KillRequest):Promise<killer.KillResult>;

export function Scan(arg1:app.Query):Promise<app.Snapshot>;
